# config/domain_tags_config.yaml
# Defines business domain tags for organizing and categorizing datasets

domain_tags:
  - tag_name: "Customer_Management"
    tag_description: >
      Data related to customer information, profiles, contact details, preferences, 
      and customer relationship management. Includes master customer data, contact 
      preferences, communication history, and customer segmentation information.
    applies_to_datasets:
      - "raw_customer_master"
      - "raw_movedaily_snapshot"
    business_priority: "High"
    data_sensitivity: "PII Present"
    
  - tag_name: "Operations"
    tag_description: >
      Operational data covering service delivery, logistics, crew management, 
      scheduling, and move execution. Includes move orders, service tracking, 
      resource allocation, and operational efficiency metrics.
    applies_to_datasets:
      - "raw_move_orders"
    business_priority: "High"
    data_sensitivity: "Business Critical"
    
  - tag_name: "Marketing"
    tag_description: >
      Marketing and lead generation data including lead sources, campaign tracking, 
      opt-in preferences, and customer acquisition metrics. Used for marketing 
      attribution, campaign effectiveness, and customer acquisition analysis.
    applies_to_datasets:
      - "raw_customer_master"
      - "raw_movedaily_snapshot"
    business_priority: "Medium"
    data_sensitivity: "Marketing Sensitive"
    
  - tag_name: "Sales"
    tag_description: >
      Sales process data covering lead management, conversion tracking, sales 
      pipeline, and revenue generation activities. Includes customer status, 
      booking information, and sales performance metrics.
    applies_to_datasets:
      - "raw_customer_master"
      - "raw_move_orders"
      - "raw_movedaily_snapshot"
    business_priority: "High"
    data_sensitivity: "Business Critical"
    
  - tag_name: "Customer_Service"
    tag_description: >
      Customer service and satisfaction data including service ratings, 
      customer feedback, service quality metrics, and customer experience 
      tracking for continuous improvement initiatives.
    applies_to_datasets:
      - "raw_move_orders"
    business_priority: "Medium"
    data_sensitivity: "Internal"
    
  - tag_name: "Logistics"
    tag_description: >
      Logistics and transportation data covering move distances, routing, 
      crew assignments, resource planning, and operational logistics for 
      service delivery optimization and capacity planning.
    applies_to_datasets:
      - "raw_move_orders"
    business_priority: "High"
    data_sensitivity: "Internal"
    
  - tag_name: "Financial"
    tag_description: >
      Financial and pricing data related to move costs, pricing models, 
      revenue tracking, and financial performance metrics for business 
      analysis and financial reporting purposes.
    applies_to_datasets:
      - "raw_move_orders"
    business_priority: "High"
    data_sensitivity: "Financial Sensitive"
    
  - tag_name: "Daily_Operations"
    tag_description: >
      Daily operational snapshots and reporting data used for day-to-day 
      business operations, daily reporting, and operational decision making. 
      Represents point-in-time operational views of business data.
    applies_to_datasets:
      - "raw_movedaily_snapshot"
    business_priority: "Medium"
    data_sensitivity: "Internal"

# Tag hierarchies and relationships
tag_hierarchies:
  business_functions:
    - name: "Customer_Facing"
      description: "Data directly related to customer interactions"
      includes_tags:
        - "Customer_Management"
        - "Customer_Service"
        - "Marketing"
        - "Sales"
        
    - name: "Internal_Operations"
      description: "Data related to internal business operations"
      includes_tags:
        - "Operations"
        - "Logistics"
        - "Daily_Operations"
        
    - name: "Financial_Business"
      description: "Data with financial implications or sensitivity"
      includes_tags:
        - "Financial"
        - "Sales"

# Data governance rules by domain
governance_rules:
  - domain: "Customer_Management"
    rules:
      - "PII data requires encryption at rest"
      - "Access logging required for all queries"
      - "Data retention: 7 years after last customer interaction"
      - "Anonymization required for analytics datasets"
      
  - domain: "Marketing"
    rules:
      - "Opt-out preferences must be respected"
      - "GDPR compliance required for EU customers"
      - "Campaign attribution tracking required"
      - "Regular consent verification needed"
      
  - domain: "Operations"
    rules:
      - "Real-time access required for active moves"
      - "Historical data needed for performance analysis"
      - "Integration with scheduling systems required"
      - "Quality metrics tracking mandatory"
      
  - domain: "Financial"
    rules:
      - "Access restricted to authorized personnel"
      - "Audit trail required for all access"
      - "Monthly reconciliation required"
      - "Compliance with financial regulations"

# Query patterns by domain
domain_query_patterns:
  Customer_Management:
    common_queries:
      - "Customer profile lookups"
      - "Contact preference analysis"
      - "Customer segmentation"
      - "Duplicate customer detection"
    performance_considerations:
      - "Index on customer ID fields"
      - "Optimize for single customer lookups"
      
  Operations:
    common_queries:
      - "Daily move schedules"
      - "Crew capacity planning"
      - "Route optimization"
      - "Service quality tracking"
    performance_considerations:
      - "Index on move dates"
      - "Optimize for date range queries"
      
  Marketing:
    common_queries:
      - "Lead source analysis"
      - "Campaign effectiveness"
      - "Opt-in status reporting"
      - "Customer acquisition costs"
    performance_considerations:
      - "Index on source fields"
      - "Optimize for aggregation queries"
      
  Sales:
    common_queries:
      - "Sales pipeline analysis"
      - "Conversion rate tracking"
      - "Revenue forecasting"
      - "Customer lifetime value"
    performance_considerations:
      - "Index on status and date fields"
      - "Optimize for trend analysis queries"

# Business intelligence dashboards by domain
bi_dashboards:
  - dashboard_name: "Customer_360"
    domain_tags: ["Customer_Management", "Sales"]
    description: "Comprehensive customer view combining profile and transaction data"
    key_metrics:
      - "Total customers"
      - "Customer acquisition rate"
      - "Customer lifetime value"
      - "Churn rate"
      
  - dashboard_name: "Operations_Daily"
    domain_tags: ["Operations", "Daily_Operations"]
    description: "Daily operational metrics and performance tracking"
    key_metrics:
      - "Daily moves scheduled"
      - "Crew utilization"
      - "Service quality scores"
      - "Operational efficiency"
      
  - dashboard_name: "Marketing_Performance"
    domain_tags: ["Marketing", "Sales"]
    description: "Marketing campaign effectiveness and lead generation analysis"
    key_metrics:
      - "Lead conversion rates"
      - "Cost per acquisition"
      - "Campaign ROI"
      - "Channel effectiveness"